# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: xrqMySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

#不需要登录就可以访问的url
secure:
  ignored:
    urls:
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /login
      - /home
      - /a
      - /b
      - /d